# Generated by Django 4.0.8 on 2023-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
