# Generated by Django 4.0.8 on 2023-09-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='display_image',
        ),
    ]
